/**
 * Route Domain Entity
 * Represents a shipping route with fuel and emissions data
 */

import { VesselType, FuelType } from '../shared/types';

export interface Route {
  /** Unique identifier (auto-increment integer) */
  id?: number;
  
  /** Route identifier */
  routeId: string;
  
  /** Type of vessel */
  vesselType: VesselType | string;
  
  /** Type of fuel used */
  fuelType: FuelType | string;
  
  /** Year of operation */
  year: number;
  
  /** GHG intensity in gCO2e/MJ */
  ghgIntensity: number;
  
  /** Fuel consumption in tons */
  fuelConsumption: number;
  
  /** Distance traveled in km */
  distance: number;
  
  /** Total emissions in tons CO2e */
  totalEmissions: number;
  
  /** Whether this is a baseline route */
  isBaseline: boolean;
}

/**
 * Factory function to create a Route entity
 * Note: id is optional and will be auto-generated by the database
 */
export function createRoute(data: Omit<Route, 'id'>): Route {
  return {
    ...data,
  };
}
